# -*- coding: utf-8 -*-
"""[sub1]_emirsyah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-fUM-scQHyKCjSaPXRAd9RQaPzavEvw

# **1.IMPORT LIBRARY**
Pada tahap awal penelitian komputasional ini, berbagai library diimpor untuk menyediakan fondasi analitis yang diperlukan. NumPy digunakan sebagai alat utama dalam pengolahan data numerik, sedangkan Pandas memfasilitasi manajemen data dalam bentuk tabel yang lebih terstruktur. Untuk visualisasi, Matplotlib dan Seaborn dihadirkan guna menghasilkan representasi grafik yang informatif dan mendukung interpretasi pola data.

Selain itu, modul os membantu dalam interaksi dengan sistem berkas ketika data perlu diakses atau diorganisasi. Proses pembagian data dan pra-pengolahan dilakukan melalui train_test_split, LabelEncoder, dan StandardScaler dari scikit-learn, yang berperan penting dalam memastikan data siap digunakan dalam pemodelan. Terakhir, sejumlah algoritma seperti Linear Regression, RandomForestClassifier, serta K-Nearest Neighbors untuk klasifikasi dan regresi diimpor sebagai kerangka kerja utama dalam pembangunan dan evaluasi model prediktif.
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor

"""Untuk mengambil dataset dari web kaggle kita harus menginstall kaggle"""

pip install kaggle

"""# **1.DATA LOADING**

tahap ini kita menyambungkan key kita
"""

# Import module yang disediakan google colab

from google.colab import files
files.upload()

"""mengambil data dari path tertuju"""

import kagglehub

# Download dataset dari Kaggle
path = kagglehub.dataset_download("stealthtechnologies/predict-purity-and-price-of-honey")

print("Isi folder dataset:")
print(os.listdir(path))

"""Mengambil dataset yang berada di path tersebut dan menyimpannya di variavle df"""

# Download dataset
path = kagglehub.dataset_download("stealthtechnologies/predict-purity-and-price-of-honey")

print("Isi folder di path Kaggle:")
print(os.listdir(path))

# LANGSUNG LOAD FILE CSV
csv_path = os.path.join(path, "honey_purity_dataset.csv")
df = pd.read_csv(csv_path)

print("\nDataset berhasil dimuat!")

df.head()

"""Deskripsi Dataset

**1. CS (Color Score)**

Menunjukkan tingkat warna pada sampel madu dengan rentang 1.0–10.0.
Nilai lebih rendah menggambarkan warna madu yang lebih terang, sedangkan nilai lebih tinggi menunjukkan madu yang lebih gelap.

**2. Density (Kepadatan)**

Menggambarkan kepadatan madu pada suhu 25°C, dengan kisaran 1.21–1.86 gram/cm³.

**3. WC (Water Content / Kadar Air)**

Menunjukkan kadar air dalam sampel madu, dengan rentang 12.0%–25.0%.

**4. pH**

Menunjukkan tingkat keasaman madu, dengan nilai pH antara 2.50–7.50.

**5. EC (Electrical Conductivity / Konduktivitas Listrik)**

Mengukur konduktivitas listrik sampel madu, dinyatakan dalam milliSiemens per centimeter (mS/cm).

**6. F (Fruktosa)**

Menunjukkan kandungan fruktosa dalam madu, dengan kisaran 20–50.

**7. G (Glukosa)**

Menunjukkan kandungan glukosa dalam madu, dengan kisaran 20–45.

**8. Pollen_analysis (Analisis Serbuk Sari)**

Menggambarkan sumber floral dari sampel madu.
Nilai yang mungkin meliputi:
Clover, Wildflower, Orange Blossom, Alfalfa, Acacia, Lavender, Eucalyptus, Buckwheat, Manuka, Sage, Sunflower, Borage, Rosemary, Thyme, Heather, Tupelo, Blueberry, Chestnut, dan Avocado.

**9. Viscosity (Viskositas**)

Mengukur tingkat kekentalan madu dalam centipoise (cP), dengan rentang 1500–10.000.
Viskositas antara 2500–9500 dianggap optimal untuk menentukan kemurnian.

**10. Purity (Kemurnian)**

Variabel target yang menunjukkan tingkat kemurnian madu, dengan nilai antara 0.01–1.00.

**11. Price (Harga)**

Harga madu yang dihitung berdasarkan parameter-parameter di atas.

# **2.Exploratory Data Analysis(EDA)**

selanjutnya kita melakukan fungsi info(). dengan fungsi tersebut,Kita bisa melihat bahwa data berubah float semua kecuali pollen_analysis yang dimana merupakan catgorical feature
"""

df.info()

"""df.describe() disini berfungsi untuk menampilkan informasi statistik dari berbagai fitur.
Jumlah data: 247.903 sampel ,dataset sangat besar dan stabil untuk pemodelan.

Rentang variabel normal dan konsisten
"""

df.describe()

"""## 2.1 EDA ( Missing values and Ouliers)

cell dibawah ini memberikan informasi mengenai missing values atau nilai kosong pada setiap kolom. di dataset ini bersih tidak terdapat missing values, oleh karna itu kita tidak perlu melakukan drop column
"""

# Cek jumlah missing values per kolom
missing_values = df.isnull().sum()

print("Missing Values per Kolom:")
print(missing_values)

"""cell dibawah ini berfungsi mencari outliers dan duplikat data. disini saya menggunakan IQR METHOD untuk mengeck outliers dan fungsi duplicaed() untuk mencari data yang duplikat pada dataset.

hasilnya dataset tidak terdapat data duplikat dan tidak memiliki outliers. sehingga dipastikan data ini sudah bersih
"""

import numpy as np

# Kolom numerik saja
numeric_cols = df.select_dtypes(include=[np.number]).columns

outlier_counts = {}

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # Hitung jumlah outlier
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    outlier_counts[col] = len(outliers)

# Tampilkan jumlah outlier per kolom
print("\nJumlah Outlier per Kolom Numerik:")
for col, count in outlier_counts.items():
    print(f"{col}: {count}")


duplikat_count = df.duplicated().sum()
print("Jumlah data duplikat:", duplikat_count)

"""Pengecekan outliers secara visualisasi dengaan boxplot"""

import matplotlib.pyplot as plt
import seaborn as sns

# Ambil semua kolom numerik
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Loop dan tampilkan boxplot untuk setiap kolom
for col in numeric_cols:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x=df[col], color="skyblue")
    plt.title(f"Boxplot Outlier – {col}")
    plt.xlabel(col)
    plt.show()

"""##2.2 Univariate EDA

Tahap ini kita akan diperlihatkan distirbusi dari masing masing setiap kolomnya,Distribusi variabel Price menunjukkan pola yang tidak sepenuhnya simetris, dengan kecenderungan sedikit right-skewed (miring ke kanan). Hal ini terlihat dari konsentrasi frekuensi yang lebih tinggi pada rentang harga menengah (sekitar 500–700). dan kolom purity dterlihat memiliki perbedaan yang siginifikan
"""

# Ambil semua fitur
numeric_features = df.select_dtypes(include=['int64', 'float64']).columns

# Loop distribusi fitur numerik
for feature in numeric_features:
    print("="*60)
    print(f"Distribusi Fitur Numerik: {feature}")
    print("="*60)

    plt.figure(figsize=(8,5))
    sns.histplot(df[feature], kde=True, bins=30)
    plt.title(f"Distribusi : {feature}")
    plt.xlabel(feature)
    plt.ylabel("Frequency")
    plt.show()

"""##2.2 Multivariate EDA
ditahap ini kita akan mengecek korelasi antar fitur numerik

Secara keseluruhan, baris yang menunjukkan hubungan Price dengan seluruh fitur lain pada pairplot menggambarkan bahwa sebagian besar variabel tidak memiliki korelasi yang jelas dengan Price. Pola titik-titiknya acak tanpa arah yang konsisten, sehingga tidak terlihat adanya pengaruh langsung dari fitur seperti density, wc, pt, oks, suhu, waktu, daya, maupun ukuran terhadap perubahan harga. Hal ini menunjukkan bahwa Price berdiri relatif independen dari variabel-variabel tersebut.
"""

# Pairplot
sns.pairplot(df[numeric_features], diag_kind='kde')
plt.show()

"""dibawah adalah korelasi matrix untuk melihat tingkat kekuatan korelasi antar fitur, semakin mendekati nilai -1 atau 1 maka bisa dibilang kedua fitur memilki relasi yang kuat

hasil saya disini, korelasi antarfitur lemah
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 8))
correlation_matrix = df[numeric_features].corr().round(2)

sns.heatmap(
    data=correlation_matrix,
    annot=True,
    cmap='coolwarm',
    linewidths=0.5
)

plt.title("Correlation Matrix untuk Fitur Numerik", size=20)
plt.show()

"""pada tahapan ini saya mencoba,mencari cara agar menguatkan korelasi antarfitur dengan melakukan

1.melakukan log transform kepada fitur price, Untuk mengurangi efek skewness dan menstabilkan variansi

2.menggabungkan beebrapa fitur untuk melihat bagaimana korelasinya terhadap fitur target
"""

df_new = df.copy()
#LOG TRANSFORMATION (hanya fitur skewed)
df_new['log_price'] = np.log1p(df_new['Price'])

#kombinasi fitur

df_new['F_G_ratio'] = df_new['F'] / df_new['G']               # rasio F/G
df_new['Total_sugar'] = df_new['F'] + df_new['G']            # total gula
df_new['Sugar_Water_ratio'] = (df_new['F'] + df_new['G']) / df_new['WC']   # gula:air
df_new['Density_Viscosity'] = df_new['Density'] * df_new['Viscosity']     # kombinasi

# DROP kolom kategori
df_corr = df_new.drop(columns=['Pollen_analysis'])

plt.figure(figsize=(12, 10))
correlation_matrix = df_corr.corr().round(2)

sns.heatmap(
    correlation_matrix,
    annot=True,       # angka biasa
    cmap='coolwarm',
    linewidths=0.5
)

plt.title("Correlation Matrix untuk Fitur Numerik", size=20)
plt.show()

"""Karena fitur-fitur gabungan tidak memberikan pengaruh berarti terhadap target dan hanya menambah noise pada analisis, saya memutuskan untuk menghapusnya dari dataset. Namun, log_price tetap dipertahankan karena transformasi log membantu menstabilkan variansi, memperbaiki distribusi harga yang skewed, serta meningkatkan kinerja model pada tahap pemodelan selanjutnya."""

#menghapus semua fitur tambahan
drop_cols = [
    'log_viscosity',
    'F_G_ratio',
    'Total_sugar',
    'Sugar_Water_ratio',
    'Density_Viscosity'
]

for col in drop_cols:
    if col in df_new.columns:
        df_new = df_new.drop(columns=[col])

"""# **3.DATA SPLITTING**

sebanyak 80% digunakan sebagai data latih dan karna targetnya adalah price maka kita perlu menghapus column ***'price'*** dan **'log_price'**,walaupun menggunakan tranfromasi log_price sebagai target , column price juga perlu dihapus agar tidak terjadi data leakage atau mencontek karna sesungguhnya fitur price bentuk lain dari log_price. Sementara itu, 20% sisanya menjadi data uji, yang digunakan untuk mengevaluasi apakah model mampu memprediksi dengan baik pada data yang belum pernah dilihat sebelumnya.
"""

from sklearn.model_selection import train_test_split

# Tentukan fitur dan target
X = df_new.drop(columns=['Price','log_price'])
y = df_new['log_price']


X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,       # 20% untuk test
    random_state=42,     # biar hasil konsisten
    shuffle=True         # penting untuk dataset kecil
)

print("Ukuran X_train:", X_train.shape)
print("Ukuran X_test :", X_test.shape)
print("Ukuran y_train:", y_train.shape)
print("Ukuran y_test :", y_test.shape)

"""# **4.Scaling Dan Encoding**
Di sini saya melakukan proses standardisasi untuk memastikan semua fitur numerik berada pada skala yang sama sebelum masuk ke model. Pertama, saya memisahkan mana fitur yang bersifat numerik dan mana yang kategorikal, karena hanya fitur numerik yang perlu distandardisasi. Setelah itu, saya menerapkan StandardScaler dan melakukan fit hanya pada data training agar tidak terjadi kebocoran informasi dari data test.
"""

from sklearn.preprocessing import StandardScaler

#Pisahkan fitur numerik dan kategorikal
numeric_cols = X_train.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = X_train.select_dtypes(include=['object']).columns

print("Fitur numerik :", list(numeric_cols))
print("Fitur kategorikal :", list(categorical_cols))

scaler = StandardScaler()

# Fit scaler hanya pada data training
X_train_scaled = X_train.copy()
X_train_scaled[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])

X_test_scaled = X_test.copy()
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])

print("\nStandardisasi selesai!")
print("Contoh hasil scaling:")
print(X_train_scaled.head())

"""Di sini saya melakukan proses encoding untuk mengubah fitur kategorikal Pollen_analysis menjadi bentuk numerik agar dapat diproses oleh model machine learning. Saya menggunakan OneHotEncoder,karena metode ini sangat cocok untuk fitur kategorikal yang tidak memiliki urutan (non-ordinal). Pollen_analysis termasuk tipe kategori yang hanya menunjukkan kelompok"""

from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Encoder untuk kategori
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit pada X_train
encoded_train = encoder.fit_transform(X_train_scaled[['Pollen_analysis']])
encoded_test = encoder.transform(X_test_scaled[['Pollen_analysis']])

encoded_train_df = pd.DataFrame(
    encoded_train,
    columns=encoder.get_feature_names_out(['Pollen_analysis']),
    index=X_train_scaled.index
)

encoded_test_df = pd.DataFrame(
    encoded_test,
    columns=encoder.get_feature_names_out(['Pollen_analysis']),
    index=X_test_scaled.index
)

# Buang kolom kategori asli
X_train_final = X_train_scaled.drop(columns=['Pollen_analysis'])
X_test_final = X_test_scaled.drop(columns=['Pollen_analysis'])

# Gabungkan kembali
X_train_final = pd.concat([X_train_final, encoded_train_df], axis=1)
X_test_final = pd.concat([X_test_final, encoded_test_df], axis=1)

print("Encoding selesai!")
print(X_train_final.head())

"""# **5.Training model**

Pada tahap ini, saya mulai membandingkan beberapa algoritma regresi, yaitu **KNN Regressor, Random Forest, dan AdaBoost**, untuk melihat model mana yang mampu memberikan performa terbaik dalam memprediksi nilai log_price. Masing-masing model saya latih menggunakan data yang sudah melalui proses scaling dan encoding, kemudian saya hitung nilai MSE *(Mean Squared Error*) baik pada data training maupun data testing untuk mengukur seberapa besar kesalahan prediksinya.

Karena hubungan antar fitur dalam dataset ini cenderung lemah dan tidak ada korelasi yang dominan, saya melakukan percobaan parameter secara berulang pada semua model. Tujuannya adalah untuk mencari kombinasi parameter yang paling stabil dan mampu menangkap pola halus yang tidak terlihat secara linear

dan dari tahapa ini memperlihatkan bahwa model memiliki **error yang kecil** sehingga model bisa dibilang bagus

**hasilnya:**
AdaBoost menjadi model terbaik karena memiliki MSE paling kecil pada training maupun testing, diikuti oleh KNN, sedangkan Random Forest memiliki error terbesar sehingga kurang optimal dibanding model lainnya.
"""

from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

X_train_use = X_train_final
X_test_use  = X_test_final

models = pd.DataFrame(index=['train_mse', 'test_mse'],
                      columns=['KNN', 'RandomForest', 'Boosting'])

# 1. KNN Regressor
knn = KNeighborsRegressor(
    n_neighbors=7,
    metric='minkowski',
    p=2
)
knn.fit(X_train_use, y_train)

models.loc['train_mse', 'KNN'] = mean_squared_error(y_train, knn.predict(X_train_use))
models.loc['test_mse', 'KNN']  = mean_squared_error(y_test,  knn.predict(X_test_use))



# 2. Random Forest

rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=10,
    min_samples_split=6,
    min_samples_leaf=3,
    max_features='sqrt',
    bootstrap=True,
    random_state=55
)
rf.fit(X_train_use, y_train)

models.loc['train_mse', 'RandomForest'] = mean_squared_error(y_train, rf.predict(X_train_use))
models.loc['test_mse', 'RandomForest']  = mean_squared_error(y_test,  rf.predict(X_test_use))


# 3. AdaBoost Regressor

base_tree = DecisionTreeRegressor(
    max_depth=5,
    min_samples_leaf=4
)

boosting = AdaBoostRegressor(
    estimator=base_tree,
    n_estimators=250,
    learning_rate=0.08,
    random_state=55
)
boosting.fit(X_train_use, y_train)

models.loc['train_mse', 'Boosting'] = mean_squared_error(y_train, boosting.predict(X_train_use))
models.loc['test_mse', 'Boosting']  = mean_squared_error(y_test,  boosting.predict(X_test_use))

print("Hasil MSE tiap model:")
print(models)

"""# **6.Evalausi**
sebelumnya saya sudah menampilkan evaluasi MSE. selanjutnya,
Blok ini menjalankan tiga model non-linear (KNN, Random Forest, AdaBoost) pada data latih dan uji, lalu mencatat RMSE dan R² di skala log_price. Hasilnya disusun dalam tabel agar cepat melihat perbandingan akurasi dan overfitting (selisih RMSE/R² antara train vs test) antar model sebelum dilakukan konversi ke harga asli
"""

from sklearn.metrics import mean_squared_error, r2_score
eval_results = pd.DataFrame(index=['RMSE_train', 'RMSE_test',
                                   'R2_train', 'R2_test'],
                            columns=['KNN', 'RandomForest', 'Boosting'])


# 1. KNN Regression
y_pred_train_knn = knn.predict(X_train_use)
y_pred_test_knn  = knn.predict(X_test_use)

eval_results.loc['RMSE_train', 'KNN'] = np.sqrt(mean_squared_error(y_train, y_pred_train_knn))
eval_results.loc['RMS E_test',  'KNN'] = np.sqrt(mean_squared_error(y_test,  y_pred_test_knn))

eval_results.loc['R2_train',   'KNN'] = r2_score(y_train, y_pred_train_knn)
eval_results.loc['R2_test',    'KNN'] = r2_score(y_test,  y_pred_test_knn)



# 2. Random Forest Regression
y_pred_train_rf = rf.predict(X_train_use)
y_pred_test_rf  = rf.predict(X_test_use)

eval_results.loc['RMSE_train', 'RandomForest'] = np.sqrt(mean_squared_error(y_train, y_pred_train_rf))
eval_results.loc['RMSE_test',  'RandomForest'] = np.sqrt(mean_squared_error(y_test,  y_pred_test_rf))

eval_results.loc['R2_train',   'RandomForest'] = r2_score(y_train, y_pred_train_rf)
eval_results.loc['R2_test',    'RandomForest'] = r2_score(y_test,  y_pred_test_rf)


# 3. AdaBoost Regression
y_pred_train_boost = boosting.predict(X_train_use)
y_pred_test_boost  = boosting.predict(X_test_use)

eval_results.loc['RMSE_train', 'Boosting'] = np.sqrt(mean_squared_error(y_train, y_pred_train_boost))
eval_results.loc['RMSE_test',  'Boosting'] = np.sqrt(mean_squared_error(y_test,  y_pred_test_boost))

eval_results.loc['R2_train',   'Boosting'] = r2_score(y_train, y_pred_train_boost)
eval_results.loc['R2_test',    'Boosting'] = r2_score(y_test,  y_pred_test_boost)


print("\nHasil Evaluasi (RMSE & R²):")
print(eval_results)

"""Melakukan interface, mengambil 1 data testing dan membandingkan dengan data aktualnya. hasilnya akurat"""

# Ambil 1 data dari test set final

prediksi = X_test_final.iloc[:1].copy()

pred_dict = {
    'y_true': y_test.iloc[:1].values[0]
}
model_loc = {
    'KNN': knn,
    'RandomForest': rf,
    'Boosting': boosting
}


# Loop model untuk prediksi
for name, model in model_loc.items():
    pred_value = model.predict(prediksi)[0]
    pred_dict['prediksi_' + name] = round(pred_value, 1)

pd.DataFrame([pred_dict])

"""Proses evaluasi dimulai dari pelatihan model Linear Regression sebagai baseline, lalu menghitung RMSE dan R² di skala log. Untuk mengukur ketidakpastian, dilakukan bootstrap 200 kali untuk membentuk interval kepercayaan RMSE. Prediksi log_price selanjutnya dikonversi ke harga asli menggunakan eksponen, dan dihitung MAPE serta RMSE di skala rupiah agar error bisa langsung dipahami dalam satuan nilai sebenarnya."""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.utils import resample

#baseline
baseline = LinearRegression()
baseline.fit(X_train_use, y_train)

y_pred_train_lr = baseline.predict(X_train_use)
y_pred_test_lr  = baseline.predict(X_test_use)

eval_results['LinearReg'] = [
    np.sqrt(mean_squared_error(y_train, y_pred_train_lr)),
    np.sqrt(mean_squared_error(y_test,  y_pred_test_lr)),
    r2_score(y_train, y_pred_train_lr),
    r2_score(y_test,  y_pred_test_lr)
]

# bootstrap
def bootstrap_rmse_ci(y_true, y_pred, n_bootstrap=200, ci=0.95):
    boot_rmse = []
    n = len(y_true)

    for _ in range(n_bootstrap):
        idx = resample(range(n), replace=True, n_samples=n)
        rmse = np.sqrt(np.mean((y_true[idx] - y_pred[idx]) ** 2))
        boot_rmse.append(rmse)

    lower = np.percentile(boot_rmse, (1-ci)/2 * 100)
    upper = np.percentile(boot_rmse, (1+ci)/2 * 100)
    return (lower, upper)

y_pred_test_knn   = knn.predict(X_test_use)
y_pred_test_rf    = rf.predict(X_test_use)
y_pred_test_boost = boosting.predict(X_test_use)

ci_results = {
    "KNN": bootstrap_rmse_ci(y_test.values, y_pred_test_knn),
    "RandomForest": bootstrap_rmse_ci(y_test.values, y_pred_test_rf),
    "Boosting": bootstrap_rmse_ci(y_test.values, y_pred_test_boost),
    "LinearReg": bootstrap_rmse_ci(y_test.values, y_pred_test_lr)
}

# inverse ke harga asli
def inverse_log(x):
    return np.exp(x)

y_true = inverse_log(y_test)
y_knn  = inverse_log(y_pred_test_knn)
y_rf   = inverse_log(y_pred_test_rf)
y_boost = inverse_log(y_pred_test_boost)
y_lr    = inverse_log(y_pred_test_lr)


def MAPE(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

mape_results = pd.DataFrame({
    "KNN":           [MAPE(y_true, y_knn)],
    "RandomForest":  [MAPE(y_true, y_rf)],
    "Boosting":      [MAPE(y_true, y_boost)],
    "LinearReg":     [MAPE(y_true, y_lr)]
}, index=["MAPE (%)"])

rmse_real = pd.DataFrame({
    "KNN":          [np.sqrt(mean_squared_error(y_true, y_knn))],
    "RandomForest": [np.sqrt(mean_squared_error(y_true, y_rf))],
    "Boosting":     [np.sqrt(mean_squared_error(y_true, y_boost))],
    "LinearReg":    [np.sqrt(mean_squared_error(y_true, y_lr))]
}, index=["RMSE (Harga Asli)"])

print("Confidence Interval RMSE (Log Scale):")
print(ci_results)

print("\nMAPE (Harga Asli):")
print(mape_results)

print("\nRMSE (Harga Asli):")
print(rmse_real)

df_new.head()

"""# **MODELING DAN EVALUASI (Linear Regression)**

Setelah melakukan evaluasi terhadap model-model sebelumnya (KNN, Random Forest, dan Boosting), pada tahap ini saya ingin membuktikan bagaimana performa model Linear Regression ketika digunakan langsung pada data dengan skala harga asli (tanpa transformasi log). Pendekatan ini dilakukan untuk melihat apakah Linear Regression mampu memberikan hasil prediksi yang stabil dan interpretable setelah proses encoding dan preprocessing diterapkan melalui pipeline.

hasil dari modeling ini bisa dibilang bagus karna hasil prediksi mendekati harga aslinya
"""

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error


# 1. Pisahkan fitur dan target khusus Linear Regression
X_linreg = df_new.drop(columns=['Price', 'log_price'])
y_linreg = df_new['Price']

# 2. Identifikasi fitur numerik & kategori
cat_features_lr = ['Pollen_analysis']
num_features_lr = [c for c in X_linreg.columns if c not in cat_features_lr]

# 3. Preprocessor untuk Linear Regression
preprocessor_lr = ColumnTransformer([
    ('categorical', OneHotEncoder(drop='first'), cat_features_lr),
    ('numerical', 'passthrough', num_features_lr)
])

# 4. Pipeline Linear Regression
model_lr = Pipeline([
    ('preprocess', preprocessor_lr),
    ('lr', LinearRegression())
])

# 5. Split data
X_train_lr, X_test_lr, y_train_lr, y_test_lr = train_test_split(
    X_linreg, y_linreg, test_size=0.2, random_state=42
)

# 6. Train
model_lr.fit(X_train_lr, y_train_lr)

# 7. Predict
y_pred_lr = model_lr.predict(X_test_lr)

# 8. Evaluasi
rmse_lr = np.sqrt(mean_squared_error(y_test_lr, y_pred_lr))
mape_lr = mean_absolute_percentage_error(y_test_lr, y_pred_lr) * 100

print("RMSE (Linear Regression):", rmse_lr)
print("MAPE (%) (Linear Regression):", mape_lr)

# Ambil sampel lr
X_sample = X_test_lr.sample(1, random_state=42)

y_sample = y_test_lr.loc[X_sample.index]
y_sample_pred = model_lr.predict(X_sample)

sample_results = pd.DataFrame({
    'Actual Price': y_sample.values,
    'Predicted Price': y_sample_pred
})

print(sample_results)

